data:
  csv_files:
  - gaze.csv
  - fixations.csv
  - saccades.csv
  - blinks.csv
  - 3d_eye_states.csv
  - keystrokes.csv
dataset:
  columns:
    # - screen_fixations
    - screen_time_s
    # - keyboard_fixations
    # - keyboard_time_s
    # - transitions
    # - path_length_px
    # - median_distance_from_previous_px
    # - std_distance_from_previous_px
    # - max_distance_from_previous_px
    # - min_distance_from_previous_px
    # - median_angle_from_previous_rad
    # - std_angle_from_previous_rad
    # - max_angle_from_previous_rad
    # - min_angle_from_previous_rad
    # - median_time_since_previous_s
    - std_time_since_previous_s
    # - max_time_since_previous_s
    # - min_time_since_previous_s
    - median_dispersion_px
    # - std_dispersion_px
    # - max_dispersion_px
    # - min_dispersion_px
    - total_saccades
    # - median_saccade_duration_s
    # - std_saccade_duration_s
    # - max_saccade_duration_s
    # - min_saccade_duration_s
    # - median_amplitude_px
    # - std_amplitude_px
    # - max_amplitude_px
    # - min_amplitude_px
    # - median_amplitude_deg
    # - std_amplitude_deg
    # - max_amplitude_deg
    # - min_amplitude_deg
    - median_mean_velocity_px_s
    # - std_mean_velocity_px_s
    # - max_mean_velocity_px_s
    # - min_mean_velocity_px_s
    - median_peak_velocity_px_s
    # - std_peak_velocity_px_s
    # - max_peak_velocity_px_s
    # - min_peak_velocity_px_s
    # - median_sequence_ratio
    # - std_sequence_ratio
    # - max_sequence_ratio
    # - min_sequence_ratio
    # - median_q_ratio
    # - std_q_ratio
    # - max_q_ratio
    # - min_q_ratio
    # - total_blinks
    # - median_blink_duration_s
    # - std_blink_duration_s
    # - max_blink_duration_s
    # - min_blink_duration_s
    # - median_pupil_diameter_left_mm
    # - std_pupil_diameter_left_mm
    # - max_pupil_diameter_left_mm
    # - min_pupil_diameter_left_mm
    # - median_pupil_diameter_right_mm
    # - std_pupil_diameter_right_mm
    # - max_pupil_diameter_right_mm
    - min_pupil_diameter_right_mm
    # - median_eyelid_aperture_left_mm
    # - std_eyelid_aperture_left_mm
    # - max_eyelid_aperture_left_mm
    # - min_eyelid_aperture_left_mm
    # - median_eyelid_aperture_right_mm
    # - std_eyelid_aperture_right_mm
    - max_eyelid_aperture_right_mm
    # - min_eyelid_aperture_right_mm
    # - median_distance_between_pupils_center_mm
    # - std_distance_between_pupils_center_mm
    # - max_distance_between_pupils_center_mm
    # - min_distance_between_pupils_center_mm
    # - keystrokes_needed
    # - keystrokes_per_sec
    # - phase_duration_s
  target: label
model:
  hyperparameters:
    learning_rate: 0.001
    batch_size: 16
    max_epochs: 1000
    patience: 10
    validation_size: 0.15
    test_size: 0.15
  architecture:
    hidden_size: 64
    num_layers: 1
    dropout: 0.3
